

INSERT INTO product ( name, category, price) VALUES ( 'omnis quod consequatur', 'Games', 184.83);
INSERT INTO product ( name, category, price) VALUES ( 'vel libero suscipit', 'Toys', 12.66);
INSERT INTO product ( name, category, price) VALUES ( 'non nemo iure', 'Grocery', 498.02);
INSERT INTO product ( name, category, price) VALUES ( 'voluptatem voluptas aspernatur', 'Toys', 536.80);
INSERT INTO product ( name, category, price) VALUES ( 'animi cum rem', 'Games', 458.20);
INSERT INTO product ( name, category, price) VALUES ( 'dolorem porro debitis', 'Toys', 146.52);
INSERT INTO product ( name, category, price) VALUES ( 'aspernatur rerum qui', 'Books', 656.42);
INSERT INTO product ( name, category, price) VALUES ( 'deleniti earum et', 'Baby', 41.46);
INSERT INTO product ( name, category, price) VALUES ( 'voluptas ut quidem', 'Books', 697.57);
INSERT INTO product ( name, category, price) VALUES ( 'eos sed debitis', 'Baby', 366.90);
INSERT INTO product ( name, category, price) VALUES ( 'laudantium sit nihil', 'Toys', 95.50);
INSERT INTO product ( name, category, price) VALUES ( 'ut perferendis corporis', 'Grocery', 302.19);
INSERT INTO product ( name, category, price) VALUES ( 'sint voluptatem ut', 'Toys', 295.37);
INSERT INTO product ( name, category, price) VALUES ( 'quos sunt ipsam', 'Grocery', 534.64);
INSERT INTO product ( name, category, price) VALUES ( 'qui illo error', 'Baby', 623.58);
INSERT INTO product ( name, category, price) VALUES ( 'aut ex ducimus', 'Books', 551.39);
INSERT INTO product ( name, category, price) VALUES ( 'accusamus repellendus minus', 'Books', 240.58);
INSERT INTO product ( name, category, price) VALUES ( 'aut accusamus quia', 'Baby', 881.38);
INSERT INTO product ( name, category, price) VALUES ( 'doloremque incidunt sed', 'Games', 988.49);
INSERT INTO product ( name, category, price) VALUES ( 'libero omnis velit', 'Baby', 177.61);
INSERT INTO product ( name, category, price) VALUES ( 'consectetur cupiditate sunt', 'Toys', 95.46);
INSERT INTO product ( name, category, price) VALUES ( 'itaque ea qui', 'Baby', 677.78);
INSERT INTO product ( name, category, price) VALUES ( 'non et nulla', 'Grocery', 70.49);
INSERT INTO product ( name, category, price) VALUES ( 'veniam consequatur et', 'Books', 893.44);
INSERT INTO product ( name, category, price) VALUES ( 'magnam adipisci voluptate', 'Grocery', 366.13);
INSERT INTO product ( name, category, price) VALUES ( 'reiciendis consequuntur placeat', 'Toys', 359.27);
INSERT INTO product ( name, category, price) VALUES ( 'dolores ipsum sit', 'Toys', 786.99);
INSERT INTO product ( name, category, price) VALUES ( 'ut hic tempore', 'Toys', 316.09);
INSERT INTO product ( name, category, price) VALUES ( 'quas quis deserunt', 'Toys', 772.78);
INSERT INTO product ( name, category, price) VALUES ( 'excepturi nesciunt accusantium', 'Toys', 911.46);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-28', '2021-03-08', 'NEW', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-28', '2021-03-05', 'NEW', 3);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-22', '2021-03-27', 'PENDING', 3);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-04', '2021-03-12', 'NEW', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-30', '2021-04-07', 'DELIVERED', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-05', '2021-03-09', 'PENDING', 8);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-27', '2021-04-05', 'NEW', 4);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-14', '2021-04-18', 'NEW', 10);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-10', '2021-03-19', 'NEW', 8);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-01', '2021-04-04', 'DELIVERED', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-24', '2021-02-28', 'PENDING', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-15', '2021-03-21', 'NEW', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-30', '2021-04-07', 'PENDING', 4);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-13', '2021-03-14', 'DELIVERED', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-13', '2021-03-21', 'NEW', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-31', '2021-03-31', 'DELIVERED', 6);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-25', '2021-03-31', 'PENDING', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-28', '2021-03-09', 'DELIVERED', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-23', '2021-03-30', 'NEW', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-19', '2021-03-24', 'DELIVERED', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-27', '2021-03-01', 'NEW', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-19', '2021-04-24', 'PENDING', 4);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-24', '2021-03-24', 'DELIVERED', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-03', '2021-03-10', 'NEW', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-20', '2021-03-25', 'NEW', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-09', '2021-04-16', 'DELIVERED', 2);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-06', '2021-04-08', 'PENDING', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-19', '2021-04-20', 'DELIVERED', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-03', '2021-03-04', 'NEW', 3);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-15', '2021-03-24', 'DELIVERED', 2);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-18', '2021-04-24', 'PENDING', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-28', '2021-03-28', 'NEW', 6);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-15', '2021-03-17', 'NEW', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-04', '2021-03-08', 'DELIVERED', 2);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-18', '2021-03-25', 'NEW', 8);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-11', '2021-04-20', 'NEW', 8);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-12', '2021-04-17', 'NEW', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-12', '2021-03-12', 'PENDING', 3);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-02-24', '2021-02-26', 'NEW', 5);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-08', '2021-04-14', 'DELIVERED', 9);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-03', '2021-03-11', 'NEW', 3);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-12', '2021-03-14', 'DELIVERED', 4);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-01', '2021-04-06', 'DELIVERED', 1);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-16', '2021-03-22', 'NEW', 10);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-07', '2021-04-12', 'PENDING', 2);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-05', '2021-04-06', 'NEW', 2);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-04-10', '2021-04-13', 'NEW', 7);
INSERT INTO product_order ( order_date, delivery_date, status, customer_id) VALUES ( '2021-03-18', '2021-03-21', 'NEW', 9);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (1, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (1, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (1, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (2, 17);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (2, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (2, 14);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (2, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (3, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (3, 3);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (3, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (3, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (3, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (4, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (4, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (4, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (5, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (6, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (6, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 25);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 1);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (7, 10);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (8, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (8, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (9, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (10, 14);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (10, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 27);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (11, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (12, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (12, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (12, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (12, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (13, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (13, 24);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (13, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (13, 23);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (14, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (15, 16);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (15, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (15, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 23);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 16);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (16, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (17, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (17, 4);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (18, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (18, 3);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (18, 27);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (18, 2);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 14);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (19, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (20, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (21, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (21, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (22, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (22, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (23, 27);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (23, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (23, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (23, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (24, 24);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (24, 2);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (24, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (24, 28);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (24, 4);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (25, 28);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (25, 17);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (25, 2);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (25, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (25, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (26, 4);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (27, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (27, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (27, 24);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (28, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (28, 9);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (29, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (30, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (30, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (30, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (31, 16);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (31, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (31, 28);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (32, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (32, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 23);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (33, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 1);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 22);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (34, 27);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (35, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (35, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (35, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (35, 9);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (36, 28);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (36, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (37, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (37, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (38, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (38, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (38, 14);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (38, 20);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (38, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (39, 1);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (39, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (40, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (40, 10);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (40, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (40, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (40, 1);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 14);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (41, 4);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (42, 2);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (43, 6);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 20);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 18);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 8);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 24);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (44, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (45, 23);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (45, 1);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (45, 25);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (45, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (46, 16);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (46, 24);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (46, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (46, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (46, 11);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (47, 23);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (47, 28);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (47, 20);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (47, 21);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 3);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 26);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 7);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 19);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (48, 10);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 5);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 13);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 29);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 3);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 12);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (49, 17);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (50, 15);
INSERT INTO order_product_relationship (order_id, product_id) VALUES (50, 16);
